version: '3.8'

services:

  # --- Conteneur PHP ---
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app_php
    ports:
      - "8080:80"              # accès à l'app via localhost:8080
    volumes:
      - .:/var/www/html        # ton code local est partagé dans le conteneur
    depends_on:
      - db                     # php démarre après la base de données

  # --- Conteneur MySQL ---
  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_depenses
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3308:3306"            # permet de te connecter avec MySQL Workbench
    volumes:
      - db_data:/var/lib/mysql # les données persistent même si tu arrêtes Docker

# --- Volume nommé pour la BDD ---
volumes:
  db_data:
